info:
  namespace: neonfishing

font_images:
  fishing_bar_0:
    path: font/fishing_bar_0.png
    suggest_in_command: false
    y_position: 10
    scale_ratio: 20
  fishing_bar_1:
    path: font/fishing_bar_1.png
    suggest_in_command: false
    y_position: 10
    scale_ratio: 20
  fishing_bar_2:
    path: font/fishing_bar_2.png
    suggest_in_command: false
    y_position: 10
    scale_ratio: 20
  fishing_bar_3:
    path: font/fishing_bar_3.png
    suggest_in_command: false
    y_position: 10
    scale_ratio: 20
  fishing_bar_4:
    path: font/fishing_bar_4.png
    suggest_in_command: false
    y_position: 10
    scale_ratio: 20
  fishing_bar_5:
    path: font/fishing_bar_5.png
    suggest_in_command: false
    y_position: 10
    scale_ratio: 20
  fishing_bar_6:
    path: font/fishing_bar_6.png
    suggest_in_command: false
    y_position: 10
    scale_ratio: 20
  fishing_bar_7:
    path: font/fishing_bar_7.png
    suggest_in_command: false
    y_position: 10
    scale_ratio: 20
  fishing_bar_8:
    path: font/fishing_bar_8.png
    suggest_in_command: false
    y_position: 10
    scale_ratio: 20
  fishing_bar_9:
    path: font/fishing_bar_9.png
    suggest_in_command: false
    y_position: 10
    scale_ratio: 20
  fishing_bar_10:
    path: font/fishing_bar_10.png
    suggest_in_command: false
    y_position: 10
    scale_ratio: 20
  fishing_cursor:
    path: font/fishing_cursor.png
    suggest_in_command: false
    y_position: 14
    scale_ratio: 20
